#!/bin/bash
#SBATCH --nodes=1
#SBATCH --partition=GPU
#SBATCH --ntasks-per-node=1
#SBATCH --time=96:00:00
#SBATCH --gres=gpu:4
#SBATCH --mem=16G
#SBATCH --nodelist=compute-0-[9]
#SBATCH --mail-type=END,FAIL             # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=stirumal@andrew.cmu.edu     # Where to send mail

set -x
set -u
set -e
module load singularity
module load cuda-80

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=0 singularity exec --nv /home/stirumal/singularity/pytorch.sif python train.py -lr 1e-3  -wd 0 -m 0.9 -ss 30 -g 0.5 -bs 8 -e 300 -dp /scratch/sashank/11785_project/dataset/test  -rp /scratch/sashank/11785_project/runs -t False -nc 2 -nf 2 